import { Product, Category, Review, Order, User, Address } from '@/types'

export const categories: Category[] = [
  { id: '1', name: 'Elektronik', icon: '💻', slug: 'elektronik', productCount: 1240, color: 'bg-blue-100 text-blue-600' },
  { id: '2', name: 'Fashion', icon: '👗', slug: 'fashion', productCount: 3210, color: 'bg-pink-100 text-pink-600' },
  { id: '3', name: 'Kecantikan', icon: '💄', slug: 'kecantikan', productCount: 890, color: 'bg-purple-100 text-purple-600' },
  { id: '4', name: 'Olahraga', icon: '⚽', slug: 'olahraga', productCount: 650, color: 'bg-green-100 text-green-600' },
  { id: '5', name: 'Rumah & Dapur', icon: '🏠', slug: 'rumah-dapur', productCount: 1100, color: 'bg-yellow-100 text-yellow-600' },
  { id: '6', name: 'Makanan', icon: '🍜', slug: 'makanan', productCount: 420, color: 'bg-orange-100 text-orange-600' },
  { id: '7', name: 'Buku', icon: '📚', slug: 'buku', productCount: 330, color: 'bg-teal-100 text-teal-600' },
  { id: '8', name: 'Mainan', icon: '🎮', slug: 'mainan', productCount: 210, color: 'bg-red-100 text-red-600' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Wireless Earbuds Pro X200',
    slug: 'wireless-earbuds-pro-x200',
    price: 299000,
    resellerPrice: 249000,
    originalPrice: 399000,
    images: [
      'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=600',
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600',
    ],
    category: 'Elektronik',
    categoryId: '1',
    rating: 4.7,
    reviewCount: 1280,
    sold: 5420,
    stock: 150,
    description: 'Wireless earbuds dengan teknologi Active Noise Cancelling terdepan. Nikmati musik dengan kualitas suara jernih dan bass yang kuat. Daya tahan baterai hingga 30 jam dengan charging case.',
    variants: [
      { id: 'v1', type: 'color', label: 'Warna', options: [
        { id: 'black', value: 'Hitam', stock: 80 },
        { id: 'white', value: 'Putih', stock: 50 },
        { id: 'blue', value: 'Biru', stock: 20 },
      ]},
    ],
    seller: { id: 's1', name: 'TechStore Official', avatar: 'https://picsum.photos/seed/s1/60', rating: 4.9, totalSales: 12500, isVerified: true, location: 'Jakarta Selatan' },
    location: 'Jakarta Selatan',
    isFlashSale: true,
    flashSalePrice: 199000,
    flashSaleEnds: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    badge: 'sale',
    tags: ['wireless', 'earbuds', 'anc', 'bluetooth'],
    weight: 200,
  },
  {
    id: '2',
    name: 'Kemeja Batik Pria Premium',
    slug: 'kemeja-batik-pria-premium',
    price: 189000,
    resellerPrice: 145000,
    originalPrice: 250000,
    images: [
      'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600',
    ],
    category: 'Fashion',
    categoryId: '2',
    rating: 4.5,
    reviewCount: 892,
    sold: 3210,
    stock: 200,
    description: 'Kemeja batik pria dengan motif khas Jawa yang elegan. Bahan katun premium 100%, nyaman dipakai seharian. Cocok untuk acara formal maupun casual.',
    variants: [
      { id: 'v2', type: 'size', label: 'Ukuran', options: [
        { id: 's', value: 'S', stock: 40 },
        { id: 'm', value: 'M', stock: 80 },
        { id: 'l', value: 'L', stock: 60 },
        { id: 'xl', value: 'XL', stock: 20 },
      ]},
      { id: 'v3', type: 'color', label: 'Motif', options: [
        { id: 'brown', value: 'Coklat Klasik', stock: 100 },
        { id: 'blue', value: 'Biru Navy', stock: 100 },
      ]},
    ],
    seller: { id: 's2', name: 'Batik Nusantara', avatar: 'https://picsum.photos/seed/s2/60', rating: 4.7, totalSales: 8900, isVerified: true, location: 'Yogyakarta' },
    location: 'Yogyakarta',
    isFlashSale: true,
    flashSalePrice: 129000,
    flashSaleEnds: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    badge: 'bestseller',
    tags: ['batik', 'kemeja', 'formal', 'pria'],
    weight: 300,
  },
  {
    id: '3',
    name: 'Serum Vitamin C Brightening 30ml',
    slug: 'serum-vitamin-c-brightening',
    price: 135000,
    resellerPrice: 105000,
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600',
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600',
    ],
    category: 'Kecantikan',
    categoryId: '3',
    rating: 4.8,
    reviewCount: 2140,
    sold: 8900,
    stock: 500,
    description: 'Serum vitamin C dengan formula advanced yang efektif mencerahkan kulit, mengurangi flek hitam, dan memberikan perlindungan antioksidan. Cocok untuk semua jenis kulit.',
    variants: [],
    seller: { id: 's3', name: 'Beautycare ID', avatar: 'https://picsum.photos/seed/s3/60', rating: 4.8, totalSales: 22000, isVerified: true, location: 'Surabaya' },
    location: 'Surabaya',
    badge: 'bestseller',
    tags: ['serum', 'vitamin c', 'skincare', 'brightening'],
    weight: 150,
  },
  {
    id: '4',
    name: 'Sepatu Running Ultraboost 4.0',
    slug: 'sepatu-running-ultraboost',
    price: 450000,
    resellerPrice: 380000,
    originalPrice: 599000,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
      'https://images.unsplash.com/photo-1556906781-9a412961a28c?w=600',
    ],
    category: 'Olahraga',
    categoryId: '4',
    rating: 4.6,
    reviewCount: 654,
    sold: 2100,
    stock: 80,
    description: 'Sepatu lari dengan teknologi Boost midsole untuk kenyamanan maksimal. Sol yang responsif memberikan energi balik saat berlari. Tersedia dalam berbagai ukuran.',
    variants: [
      { id: 'v4', type: 'size', label: 'Ukuran', options: [
        { id: '39', value: '39', stock: 15 },
        { id: '40', value: '40', stock: 20 },
        { id: '41', value: '41', stock: 25 },
        { id: '42', value: '42', stock: 15 },
        { id: '43', value: '43', stock: 5 },
      ]},
      { id: 'v5', type: 'color', label: 'Warna', options: [
        { id: 'black', value: 'Hitam', stock: 40 },
        { id: 'white', value: 'Putih', stock: 40 },
      ]},
    ],
    seller: { id: 's1', name: 'TechStore Official', avatar: 'https://picsum.photos/seed/s1/60', rating: 4.9, totalSales: 12500, isVerified: true, location: 'Jakarta Selatan' },
    location: 'Jakarta Selatan',
    badge: 'sale',
    tags: ['sepatu', 'running', 'olahraga', 'sport'],
    weight: 800,
  },
  {
    id: '5',
    name: 'Smartwatch Fitness Tracker X1',
    slug: 'smartwatch-fitness-tracker-x1',
    price: 389000,
    resellerPrice: 320000,
    originalPrice: 499000,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600',
    ],
    category: 'Elektronik',
    categoryId: '1',
    rating: 4.4,
    reviewCount: 423,
    sold: 1560,
    stock: 60,
    description: 'Smartwatch dengan fitur pemantauan detak jantung, kadar oksigen darah (SpO2), GPS, dan 100+ mode olahraga. Layar AMOLED 1.6 inch yang jernih.',
    variants: [
      { id: 'v6', type: 'color', label: 'Warna Tali', options: [
        { id: 'black', value: 'Hitam', stock: 30 },
        { id: 'silver', value: 'Silver', stock: 20 },
        { id: 'rose', value: 'Rose Gold', stock: 10 },
      ]},
    ],
    seller: { id: 's1', name: 'TechStore Official', avatar: 'https://picsum.photos/seed/s1/60', rating: 4.9, totalSales: 12500, isVerified: true, location: 'Jakarta Selatan' },
    location: 'Jakarta Selatan',
    isFlashSale: false,
    badge: 'new',
    tags: ['smartwatch', 'fitness', 'tracker', 'elektronik'],
    weight: 350,
  },
  {
    id: '6',
    name: 'Rice Cooker Digital Premium 1.8L',
    slug: 'rice-cooker-digital-premium',
    price: 265000,
    resellerPrice: 215000,
    images: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600',
    ],
    category: 'Rumah & Dapur',
    categoryId: '5',
    rating: 4.6,
    reviewCount: 1890,
    sold: 6700,
    stock: 300,
    description: 'Rice cooker digital dengan layar LCD dan 8 menu masak otomatis. Kapasitas 1.8 liter, ideal untuk keluarga. Dilengkapi teknologi keep warm 24 jam.',
    variants: [],
    seller: { id: 's2', name: 'Batik Nusantara', avatar: 'https://picsum.photos/seed/s2/60', rating: 4.7, totalSales: 8900, isVerified: true, location: 'Yogyakarta' },
    location: 'Yogyakarta',
    badge: 'bestseller',
    tags: ['rice cooker', 'dapur', 'elektronik', 'masak'],
    weight: 2500,
  },
  {
    id: '7',
    name: 'Tas Ransel Laptop Anti Air 30L',
    slug: 'tas-ransel-laptop-anti-air',
    price: 195000,
    resellerPrice: 155000,
    originalPrice: 280000,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600',
      'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600',
    ],
    category: 'Fashion',
    categoryId: '2',
    rating: 4.5,
    reviewCount: 732,
    sold: 2890,
    stock: 120,
    description: 'Tas ransel multifungsi dengan kompartemen laptop 15.6 inch, port USB charging, dan material anti air. Desain ergonomis untuk kenyamanan maksimal saat digunakan seharian.',
    variants: [
      { id: 'v7', type: 'color', label: 'Warna', options: [
        { id: 'black', value: 'Hitam', stock: 60 },
        { id: 'grey', value: 'Abu-abu', stock: 40 },
        { id: 'navy', value: 'Navy', stock: 20 },
      ]},
    ],
    seller: { id: 's3', name: 'Beautycare ID', avatar: 'https://picsum.photos/seed/s3/60', rating: 4.8, totalSales: 22000, isVerified: true, location: 'Surabaya' },
    location: 'Surabaya',
    badge: 'sale',
    tags: ['tas', 'ransel', 'laptop', 'anti air'],
    weight: 700,
  },
  {
    id: '8',
    name: 'Kopi Arabika Specialty 250g',
    slug: 'kopi-arabika-specialty',
    price: 89000,
    resellerPrice: 70000,
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600',
      'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600',
    ],
    category: 'Makanan',
    categoryId: '6',
    rating: 4.9,
    reviewCount: 3401,
    sold: 12000,
    stock: 999,
    description: 'Kopi Arabika single origin dari pegunungan Gayo, Aceh. Roasted fresh to order dengan profil rasa fruity, floral, dengan keasaman yang lembut. Tersedia dalam pilihan biji atau bubuk.',
    variants: [
      { id: 'v8', type: 'material', label: 'Jenis', options: [
        { id: 'biji', value: 'Biji Utuh', stock: 500 },
        { id: 'halus', value: 'Bubuk Halus', stock: 499 },
        { id: 'kasar', value: 'Bubuk Kasar', stock: 499 },
      ]},
    ],
    seller: { id: 's2', name: 'Batik Nusantara', avatar: 'https://picsum.photos/seed/s2/60', rating: 4.7, totalSales: 8900, isVerified: true, location: 'Yogyakarta' },
    location: 'Aceh',
    badge: 'bestseller',
    tags: ['kopi', 'arabika', 'specialty', 'gayo'],
    weight: 300,
  },
  {
    id: '9',
    name: 'Parfum Oud Elixir 50ml',
    slug: 'parfum-oud-elixir',
    price: 320000,
    resellerPrice: 260000,
    originalPrice: 420000,
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600',
    ],
    category: 'Kecantikan',
    categoryId: '3',
    rating: 4.7,
    reviewCount: 567,
    sold: 1890,
    stock: 75,
    description: 'Parfum premium dengan aroma Oud yang kuat dan tahan lama hingga 12 jam. Dibuat dari campuran bahan berkualitas tinggi dengan sentuhan timur tengah yang mewah.',
    variants: [],
    seller: { id: 's3', name: 'Beautycare ID', avatar: 'https://picsum.photos/seed/s3/60', rating: 4.8, totalSales: 22000, isVerified: true, location: 'Surabaya' },
    location: 'Surabaya',
    badge: 'new',
    tags: ['parfum', 'oud', 'fragrance', 'luxury'],
    weight: 200,
  },
  {
    id: '10',
    name: 'Matras Yoga Premium 6mm',
    slug: 'matras-yoga-premium',
    price: 175000,
    resellerPrice: 140000,
    images: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600',
    ],
    category: 'Olahraga',
    categoryId: '4',
    rating: 4.5,
    reviewCount: 445,
    sold: 1670,
    stock: 200,
    description: 'Matras yoga dengan ketebalan 6mm untuk kenyamanan optimal. Material TPE ramah lingkungan, anti slip, mudah dibersihkan. Tersedia dalam berbagai pilihan warna cerah.',
    variants: [
      { id: 'v9', type: 'color', label: 'Warna', options: [
        { id: 'purple', value: 'Ungu', stock: 50 },
        { id: 'green', value: 'Hijau', stock: 80 },
        { id: 'pink', value: 'Pink', stock: 70 },
      ]},
    ],
    seller: { id: 's1', name: 'TechStore Official', avatar: 'https://picsum.photos/seed/s1/60', rating: 4.9, totalSales: 12500, isVerified: true, location: 'Jakarta Selatan' },
    location: 'Jakarta Selatan',
    tags: ['yoga', 'matras', 'olahraga', 'fitness'],
    weight: 1200,
  },
  {
    id: '11',
    name: 'Keyboard Mechanical RGB TKL',
    slug: 'keyboard-mechanical-rgb-tkl',
    price: 485000,
    resellerPrice: 400000,
    originalPrice: 650000,
    images: [
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600',
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600',
    ],
    category: 'Elektronik',
    categoryId: '1',
    rating: 4.8,
    reviewCount: 921,
    sold: 3400,
    stock: 45,
    description: 'Keyboard mechanical TKL dengan switch Gateron Red, backlit RGB per key. Build quality premium dengan body aluminum. Hot-swappable untuk kustomisasi switch.',
    variants: [
      { id: 'v10', type: 'material', label: 'Switch', options: [
        { id: 'red', value: 'Gateron Red (Linear)', stock: 20 },
        { id: 'blue', value: 'Gateron Blue (Clicky)', stock: 15 },
        { id: 'brown', value: 'Gateron Brown (Tactile)', stock: 10 },
      ]},
    ],
    seller: { id: 's1', name: 'TechStore Official', avatar: 'https://picsum.photos/seed/s1/60', rating: 4.9, totalSales: 12500, isVerified: true, location: 'Jakarta Selatan' },
    location: 'Jakarta Selatan',
    isFlashSale: true,
    flashSalePrice: 359000,
    flashSaleEnds: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    badge: 'sale',
    tags: ['keyboard', 'mechanical', 'rgb', 'gaming'],
    weight: 900,
  },
  {
    id: '12',
    name: 'Buku "Filosofi Teras" - Henry Manampiring',
    slug: 'buku-filosofi-teras',
    price: 88000,
    resellerPrice: 68000,
    images: [
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600',
    ],
    category: 'Buku',
    categoryId: '7',
    rating: 4.9,
    reviewCount: 4521,
    sold: 18000,
    stock: 1000,
    description: 'Buku terlaris tentang filsafat Stoik yang diadaptasi dengan konteks kehidupan Indonesia modern. Panduan praktis menjalani hidup yang lebih tenang dan bermakna.',
    variants: [],
    seller: { id: 's2', name: 'Batik Nusantara', avatar: 'https://picsum.photos/seed/s2/60', rating: 4.7, totalSales: 8900, isVerified: true, location: 'Yogyakarta' },
    location: 'Yogyakarta',
    badge: 'bestseller',
    tags: ['buku', 'motivasi', 'filsafat', 'stoik'],
    weight: 400,
  },
]

export const flashSaleProducts = products.filter(p => p.isFlashSale)

export const reviews: Review[] = [
  { id: 'r1', userId: 'u1', userName: 'Andi Pratama', userAvatar: 'https://picsum.photos/seed/u1/40', rating: 5, comment: 'Produk sesuai deskripsi, kualitas bagus banget! Pengiriman juga cepat. Highly recommended!', date: '2024-01-15', variant: 'Hitam' },
  { id: 'r2', userId: 'u2', userName: 'Siti Rahayu', userAvatar: 'https://picsum.photos/seed/u2/40', rating: 4, comment: 'Produknya bagus, sesuai ekspektasi. Pengemasan rapi dan aman. Seller responsif.', date: '2024-01-12', variant: 'Putih' },
  { id: 'r3', userId: 'u3', userName: 'Budi Santoso', userAvatar: 'https://picsum.photos/seed/u3/40', rating: 5, comment: 'Luar biasa! Kualitas premium tapi harga sangat terjangkau. Sudah beli 2x dan puas.', date: '2024-01-10' },
  { id: 'r4', userId: 'u4', userName: 'Dewi Anggraini', userAvatar: 'https://picsum.photos/seed/u4/40', rating: 4, comment: 'Bagus, tapi waktu pengiriman agak lama. Produk sendiri memuaskan.', date: '2024-01-08' },
  { id: 'r5', userId: 'u5', userName: 'Rizki Maulana', userAvatar: 'https://picsum.photos/seed/u5/40', rating: 5, comment: 'Perfect! Exactly as described. Will definitely buy again. Top seller!', date: '2024-01-05', variant: 'Biru' },
]

export const mockUser: User = {
  id: 'u1',
  name: 'Raden Rifal',
  email: 'rardiansyah@kensolusindo.com',
  phone: '08123456789',
  avatar: 'https://picsum.photos/seed/user/80',
  isReseller: true,
  resellerTier: 'gold',
  joinDate: '2023-03-15',
  totalOrders: 47,
  totalSpent: 12500000,
}

export const mockAddresses: Address[] = [
  {
    id: 'a1',
    label: 'Rumah',
    recipientName: 'Raden Rifal',
    phone: '08123456789',
    province: 'DKI Jakarta',
    city: 'Jakarta Selatan',
    district: 'Kebayoran Baru',
    postalCode: '12110',
    fullAddress: 'Jl. Sudirman No. 123, RT 04/RW 02, Kebayoran Baru',
    isDefault: true,
  },
  {
    id: 'a2',
    label: 'Kantor',
    recipientName: 'Raden Rifal',
    phone: '08123456789',
    province: 'DKI Jakarta',
    city: 'Jakarta Pusat',
    district: 'Gambir',
    postalCode: '10110',
    fullAddress: 'Jl. MH Thamrin No. 56, Lantai 12, Gedung Menara Kebon Sirih',
    isDefault: false,
  },
]

export const mockOrders: Order[] = [
  {
    id: 'o1',
    orderNumber: 'EC-2024-001234',
    status: 'delivered',
    items: [{ id: 'ci1', productId: '1', product: products[0], quantity: 1, selectedVariants: { color: 'Hitam' }, price: 299000 }],
    total: 330000,
    shippingCost: 31000,
    createdAt: '2024-01-10T08:00:00Z',
    estimatedDelivery: '2024-01-13',
    trackingNumber: 'JNE12345678',
    courier: 'JNE',
    address: mockAddresses[0],
  },
  {
    id: 'o2',
    orderNumber: 'EC-2024-001567',
    status: 'shipped',
    items: [{ id: 'ci2', productId: '3', product: products[2], quantity: 2, selectedVariants: {}, price: 270000 }],
    total: 297000,
    shippingCost: 27000,
    createdAt: '2024-01-14T10:30:00Z',
    estimatedDelivery: '2024-01-17',
    trackingNumber: 'JNT98765432',
    courier: 'J&T',
    address: mockAddresses[0],
  },
  {
    id: 'o3',
    orderNumber: 'EC-2024-001890',
    status: 'processing',
    items: [{ id: 'ci3', productId: '11', product: products[10], quantity: 1, selectedVariants: { switch: 'Gateron Red (Linear)' }, price: 359000 }],
    total: 385000,
    shippingCost: 26000,
    createdAt: '2024-01-15T14:00:00Z',
    estimatedDelivery: '2024-01-18',
    courier: 'SiCepat',
    address: mockAddresses[1],
  },
]

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(price)
}

export const getDiscount = (original: number, current: number): number => {
  return Math.round((1 - current / original) * 100)
}
